#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
function() {
  local fb_prompt_file=/opt/facebook/share/scm-prompt
  if [ -f "$fb_prompt_file" ]; then
    source "$fb_prompt_file"
  else
    echo "couldn't find FB SCM prompt file ${fb_prompt_file}"
  fi
}

export USER_NAME=royr
export WORKSPACE=${BASE_PATH}/workspace

if [ `uname` = "Darwin" ]; then
    IS_MAC=true
else
    IS_MAC=false
fi
export IS_MAC

PATH="/usr/local/bin:/usr/local/sbin:/usr/local/git/bin:$PATH"
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
export PATH
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

if $IS_MAC; then
    # Add github ssh key if missing
    if [ -z "`ssh-add -l|grep github`" ] ; then 
        ssh-add ~/.ssh/github_rsa
    fi
fi

if $IS_MAC; then
    # 'brew cask' should link apps to /Applications instead of ~/Applications
    export HOMEBREW_CASK_OPTS="--appdir=/Applications"

fi
# handle Mac OS X shitty support for terminal locales
if $IS_MAC; then
    export LC_CTYPE=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
fi

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f ~/.bashrc_fb]; then
    . ~/.bashrc_fb
fi
if [ -f ~/.zshrc_fb]; then
    . ~/.zshrc_fb
fi

export EDITOR=vim
export VISUAL=vim
